export const SET_PLUS_READY = 'SET_PLUS_READY' // plus是否已经加载
export const SET_AJAX_RESULT = 'SET_AJAX_RESULT' // 设置ajax请求返回结果状态
export const SET_AGREEMENT = 'SET_AGREEMENT' // 设置登录协议内容
export const INIT_USER_INFO = 'INIT_USER_INFO' //保存用户信息（消费者或会员）
export const SET_OPENED_POPUP = 'SET_OPENED_POPUP' // 设置当前打开的popup页面
export const LOGOUT = 'LOGOUT' // 退出登录，清除用户数据和更改用户类型为访客（0）
export const SET_USER_TYPE = 'SET_USER_TYPE' // 设置用户类型，访客（0），会员（1），消费者（3）
export const SET_IS_SET_DETAIL = 'SET_IS_SET_DETAIL' // 设置会员是否已经设置详情
export const SET_CONFIRM_AGREEMENT = 'SET_CONFIRM_AGREEMENT' // 设置会员是否已经同意条款
export const SET_QRCODE = 'SET_QRCODE' // 设置会员的专属二维码
export const UPDATE_LANG = 'UPDATE_LANG' // 更新语言
export const SET_COUNTRY = 'SET_COUNTRY' // 更新国家窗口
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN' // 用户登录之后，设置axios中header的access_token
export const SET_BRANCH_COMPANY = 'SET_BRANCH_COMPANY' // 设置选中的分公司
export const SET_BRANCH_COMPANY_LIST = 'SET_BRANCH_COMPANY_LIST' // 设置分公司列表
export const SET_MY_RACE_LIST = 'SET_MY_RACE_LIST' // 设置马来西亚种族列表
export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST' //获取用户收获地址
export const SET_TIP_COUNT = 'SET_TIP_COUNT' //提示期结算
export const SET_SHOW_TERM_SETTLEMENT_INFO = 'SET_SHOW_TERM_SETTLEMENT_INFO' // 是否显示结算
export const SET_HIDE_TERM_SETTLEMENT_DATE = 'SET_HIDE_TERM_SETTLEMENT_DATE' // 今日不显示的日期
export const SET_MY_BONUS = 'SET_MY_BONUS' //获取奖金信息
export const SET_MY_WALLET = 'SET_MY_WALLET' //获取钱包信息
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST' //获取首页商品列表
export const SET_GOODS_LIST = 'SET_GOODS_LIST' //获取购货商品列表
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL' //首页产品详情页
export const SET_GET_CART = 'SET_GET_CART' //购物车
export const SET_ORDER_LIST = 'SET_ORDER_LIST' //订单列表
export const SET_HOME_INFO = 'SET_HOME_INFO' //会员首页列表
export const SET_BANNER_LIST = 'SET_BANNER_LIST' // 获取首页轮播图列表
export const SET_REGISTER_INFO = 'SET_REGISTER_INFO' //获取注册信息
export const SET_REGISTER_COUNTRY_LIST = 'SET_REGISTER_COUNTRY_LIST' // 设置注册时选择的证件国籍列表
export const SET_REGISTER_BRANCH_COUNTRY = 'SET_REGISTER_BRANCH_COUNTRY' // 设置注册时选择的国家窗口及证件国籍
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS' // 获取订单详情
export const SET_FILL_INFO_TYPE = 'SET_FILL_INFO_TYPE' // 设置填写更多信息类型
export const SET_PROVINCE_LIST = 'SET_PROVINCE_LIST' // 获取省份列表
export const SET_CITY_LIST = 'SET_CITY_LIST' // 获取城市列表
export const SET_DISTRICT_LIST = 'SET_DISTRICT_LIST' // 获取地区列表
export const SET_PAYMENT_WAY = 'SET_PAYMENT_WAY' // 支付方式
export const SET_ORDER_CONFIRM = 'SET_ORDER_CONFIRM' // 订单确认信息
export const SET_ORDER_CONFIRM_ADDRESS = 'SET_ORDER_CONFIRM_ADDRESS' // 订单确认选择的物流输送地址
export const SET_INVOICE_TYPE = 'SET_INVOICE_TYPE' // 设置发票类型
export const SET_INTRODUCER = 'SET_INTRODUCER' // 推荐者信息
export const SET_FILL_INFO_ADDR = 'SET_PERSONAL_PROVINCE' // 填写信息选择省市区
export const SET_RACE_INFO = 'SET_RACE_INFO' // 填写信息选择种族
export const SET_ADDRESS_COUNTRY_LIST = 'SET_ADDRESS_COUNTRY_LIST' // 设置地址选择国家列表
export const SET_ADDRESS_PROVINCE_LIST = 'SET_ADDRESS_PROVINCE_LIST' // 设置地址选择省份列表
export const SET_ADDRESS_CITY_LIST = 'SET_ADDRESS_CITY_LIST' // 设置地址选择城市列表
export const SET_ADDRESS_DISTRICT_LIST = 'SET_ADDRESS_DISTRICT_LIST' // 设置地址选择地区列表
export const SET_ADDRESS_INFO = 'SET_ADDRESS_INFO' // 设置选中的地址地区信息